export interface Country {
  code: string;
  flag: string;
  name: string;
}

export const COUNTRIES:Country[] = [
    { code: 'AND', flag: 'ad', name: 'Andorra' },
    { code: 'ARE', flag: 'ae', name: 'United Arab Emirates' },
    { code: 'AFG', flag: 'af', name: 'Afghanistan' },
    { code: 'ATG', flag: 'ag', name: 'Antigua and Barbuda' },
    { code: 'AIA', flag: 'ai', name: 'Anguilla' },
    { code: 'ALB', flag: 'al', name: 'Albania' },
    { code: 'ARM', flag: 'am', name: 'Armenia' },
    { code: 'AGO', flag: 'ao', name: 'Angola' },
    { code: 'ARG', flag: 'ar', name: 'Argentina' },
    { code: 'ASM', flag: 'as', name: 'American Samoa' },
    { code: 'AUT', flag: 'at', name: 'Austria' },
    { code: 'AUS', flag: 'au', name: 'Australia' },
    { code: 'ABW', flag: 'aw', name: 'Aruba' },
    { code: 'AZE', flag: 'az', name: 'Azerbaijan' },
    { code: 'BIH', flag: 'ba', name: 'Bosnia and Herzegovina' },
    { code: 'BRB', flag: 'bb', name: 'Barbados' },
    { code: 'BGD', flag: 'bd', name: 'Bangladesh' },
    { code: 'BEL', flag: 'be', name: 'Belgium' },
    { code: 'BFA', flag: 'bf', name: 'Burkina Faso' },
    { code: 'BGR', flag: 'bg', name: 'Bulgaria' },
    { code: 'BHR', flag: 'bh', name: 'Bahrain' },
    { code: 'BDI', flag: 'bi', name: 'Burundi' },
    { code: 'BEN', flag: 'bj', name: 'Benin' },
    { code: 'BRN', flag: 'bn', name: 'Brunei Darussalam' },
    { code: 'BOL', flag: 'bo', name: 'Bolivia' },
    { code: 'BRA', flag: 'br', name: 'Brazil' },
    { code: 'BHS', flag: 'bs', name: 'Bahamas' },
    { code: 'BTN', flag: 'bt', name: 'Bhutan' },
    { code: 'BWA', flag: 'bw', name: 'Botswana' },
    { code: 'BLR', flag: 'by', name: 'Belarus' },
    { code: 'BLZ', flag: 'bz', name: 'Belize' },
    { code: 'CAN', flag: 'ca', name: 'Canada' },
    { code: 'CHE', flag: 'ch', name: 'Switzerland' },
    { code: 'CHN', flag: 'cn', name: 'China' },
    { code: 'DEU', flag: 'de', name: 'Germany' },
    { code: 'DNK', flag: 'dk', name: 'Denmark' },
    { code: 'ESP', flag: 'es', name: 'Spain' },
    { code: 'FIN', flag: 'fi', name: 'Finland' },
    { code: 'FRA', flag: 'fr', name: 'France' },
    { code: 'GBR', flag: 'gb', name: 'United Kingdom' },
    { code: 'GRC', flag: 'gr', name: 'Greece' },
    { code: 'HKG', flag: 'hk', name: 'Hong Kong' },
    { code: 'HUN', flag: 'hu', name: 'Hungary' },
    { code: 'IDN', flag: 'id', name: 'Indonesia' },
    { code: 'IRL', flag: 'ie', name: 'Ireland' },
    { code: 'IND', flag: 'in', name: 'India' },
    { code: 'ISL', flag: 'is', name: 'Iceland' },
    { code: 'ITA', flag: 'it', name: 'Italy' },
    { code: 'JPN', flag: 'jp', name: 'Japan' },
    { code: 'KOR', flag: 'kr', name: 'South Korea' },
    { code: 'KWT', flag: 'kw', name: 'Kuwait' },
    { code: 'LKA', flag: 'lk', name: 'Sri Lanka' },
    { code: 'MYS', flag: 'my', name: 'Malaysia' },
    { code: 'MEX', flag: 'mx', name: 'Mexico' },
    { code: 'NLD', flag: 'nl', name: 'Netherlands' },
    { code: 'NOR', flag: 'no', name: 'Norway' },
    { code: 'NZL', flag: 'nz', name: 'New Zealand' },
    { code: 'OMN', flag: 'om', name: 'Oman' },
    { code: 'PHL', flag: 'ph', name: 'Philippines' },
    { code: 'PAK', flag: 'pk', name: 'Pakistan' },
    { code: 'QAT', flag: 'qa', name: 'Qatar' },
    { code: 'RUS', flag: 'ru', name: 'Russia' },
    { code: 'SAU', flag: 'sa', name: 'Saudi Arabia' },
    { code: 'SWE', flag: 'se', name: 'Sweden' },
    { code: 'SGP', flag: 'sg', name: 'Singapore' },
    { code: 'THA', flag: 'th', name: 'Thailand' },
    { code: 'TUR', flag: 'tr', name: 'Turkey' },
    { code: 'TWN', flag: 'tw', name: 'Taiwan' },
    { code: 'UKR', flag: 'ua', name: 'Ukraine' },
    { code: 'USA', flag: 'us', name: 'United States' },
    { code: 'VNM', flag: 'vn', name: 'Vietnam' },
    { code: 'ZAF', flag: 'za', name: 'South Africa' }
  ];